FROM mongo:4.4.5
RUN mkdir -p /app/data
WORKDIR /app/data
COPY /DATAIMPORT/* /app/data/
CMD ["mongod", "&&", "mongoimport", "-d", "atelier", "-c", "features", "--headerline", '--drop', "productsTest.csv"]
